### ISSUE TITLE
Installing using script on Mac M1 Pro

### ISSUE THREAD

**Issue by videodromejockey** [HereInPlainSight/gshade_installer#12]
Hey there,

I've been following the guide over at https://github.com/seathasky/FF14-MAC_ModSupport for running XIV over Crossover. I have the game running and am trying to get gshade working using your script per step 5. 

Unfortunately I'm hung up on running the script due to:

Creating...  The following necessary command(s) could not be found: wine
,%                                

I have Wine 5.0 installed in addition to Crossover so I'm not sure why there's a wine command missing. Advice?

**Comment by HereInPlainSight** [comment]
Based on my limited understanding, this is a bit of a path issue at the very least.

However, there's a pull request in process to make the script more friendly to Macs by someone who actually _has_ a Mac.  Hopefully this should resolve the issue, as unfortunately, I have no experience with OSX.

Leaving this open until the pull request is merged, then I'll ping the topic again so you can test it.

**Comment by seenasa** [comment]
@videodromejockey Hi there, having the same issue and was wondering if you ever got this resolved. I'm not really sure if I'm just using incorrect syntax to run the script in the wine bottle

**Comment by videodromejockey** [comment]
@ssalehian0 No, sorry, I never got this fixed. However, marzent over at FF14-MAC_ModSupport is apparently working on an easier way to get gshade working. No idea on an ETA/if it will ever be addressed.

**Comment by zoeyronain** [comment]
I have an update for this because I'm trying the same thing:

running `WINEPREFIX="/Applications/FINAL` FANTASY XIV ONLINE.app/Contents/SharedSupport/finalfantasyxiv/support/published_Final_Fantasy/" ./gshade_installer.sh ffxiv `

WILL find the game, 

<img width="1512" alt="Screen Shot 2021-12-01 at 23 39 40" src="https://user-images.githubusercontent.com/2716914/144364353-56f1b186-f205-4b9b-b79f-188759899268.png">

and install successfully from the look of it

<img width="1512" alt="Screen Shot 2021-12-01 at 23 40 13" src="https://user-images.githubusercontent.com/2716914/144364390-87882d4f-5b34-4898-8eb9-c5be04e12961.png">

but it's looking for ffxiv_dx11.exe which doesn't exist in the bottle. it's the normal ffxivboot64.exe 

<img width="1512" alt="Screen Shot 2021-12-01 at 23 49 43" src="https://user-images.githubusercontent.com/2716914/144365328-98cc0ae3-359e-45e7-b3b8-0b6bafbdfd9e.png">


The files ARE in the correct location from a normal wine/steam gshade install. I can't get the menu to load so I can pick a preset though. I manually edited the gshade.ini

<img width="1512" alt="Screen Shot 2021-12-01 at 23 53 00" src="https://user-images.githubusercontent.com/2716914/144365678-dbf287eb-574d-4c75-8262-e10b88488117.png">

I haven't restarted ffxiv yet (mad dash to finish before the game goes down for the endwalker release), but maybe it'll work?

**Comment by HereInPlainSight** [comment]
Your screenshots are... slightly conflicting.  The command line `list` indicates you're installed into `/Applications/FINAL FANTASY XIV ONLINE.app/Contents/SharedSupport/finalfantasyxiv/support/published_Final_Fantasy/drive_c/Program Files (x86)/SquareEnix/FINAL FANTASY XIV - A Realm Reborn/game/`...  but your file system screenshot indicates `../boot/` from that location.

`ffxivboot*.exe` are the launchers.  `ffxiv*.exe` is the game itself, either for dx9 or dx11 (at least, on the windows version) and are in the `game/` folder.  Normally, we attached to the game itself, which is why it was looking for `ffxiv_dx11.exe`.  I don't expect you'll get a menu by attaching to the launcher.

**Comment by zoeyronain** [comment]
You're right, I did a manual install the first time and it went into boot by accident (I think, I don't have my old laptop handy to check where it's supposed to be in windows). They're in both folders.

there is no ffxiv_dx*.exe ANYWHERE in the prefix. there is ffxivlauncher.exe and ffxivlauncher64.exe which may be the launcher in this case, and ffxivboot is the game?

**Comment by HereInPlainSight** [comment]
Well, I don't actually have access to a Mac to check anything -- all I can say is, according to the [draft](https://github.com/HereInPlainSight/gshade_installer/blob/0ffdda89efcf65f6858b0fbabd344b89aa67f437/gshade_installer.sh#L654), where things are primarily updated for Mac installs, in that whole section, `gameExe` (which by default points to `ffxiv_dx11.exe`) wasn't changed by the person working on the pull request.

What _is_ in your `game/` directory on Mac, then?

**Comment by zoeyronain** [comment]
I figured it out! 

The wineprefix in /Applications was a lie even though it looks like the entire game is installed there. the actual wineprefix location is $HOME/Library/Application Support/FINAL FANTASY XIV ONLINE/Bottles/published_Final_Fantasy

ffxiv_dx11.exe is located at $HOME/Library/Application Support/FINAL FANTASY XIV ONLINE/Bottles/published_Final_Fantasy/drive_c/Program Files (x86)/SquareEnix/FINAL FANTASY XIV - A Realm Reborn/game/ffxiv_dx11.exe

<img width="1512" alt="Screen Shot 2021-12-02 at 00 41 26" src="https://user-images.githubusercontent.com/2716914/144371191-cd2c4683-e883-40d9-8fb5-4e93bdf78e28.png">

however the menu continues to not load, and changing the gshade.ini file manually didn't appear to change anything (the FPS counter I enabled isn't showing up still)

**Comment by HereInPlainSight** [comment]
The only thing I see that doesn't quite match seathasky's guide I see you've got up is that you used the dx11 option, he used the dxgi option.  Don't forget to either override the `d3d11.dll` file instead of the `dxgi.dll` file in seathasky's guide, or reinstall to the prefix using `dxgi` instead.

Unfortunately, anything past that particular discrepancy is outside my range of knowledge.

**Comment by zoeyronain** [comment]
Ok the game just went down for 24h and I broke my install trying to get dxvk updated in the crossover bottle.

it IS possible on d3d11! somewhat. I got reshade showing up in the game but it gives an dx11 error when it starts scanning presets. and the reshade window sits at loading forever.


<img width="1512" alt="Screen Shot 2021-12-02 at 02 20 57" src="https://user-images.githubusercontent.com/2716914/144392631-fd16e7bd-720c-471b-8a05-4783003afe60.png">

Changing the config didn't work and I completely broke my install trying to update dxvk on advice from a friend.

If trying to use a straight wineprefix for xivlauncher doesn't work, I'll redownload and try again.

**Comment by HereInPlainSight** [comment]
The pull request from @marzent for better Mac compatibility has been merged in.  Auto-install does not currently work, manual installs should work, though, and be less troublesome than they were.

I'll leave the issue open for at least a month if no one comments further -- presuming that no news would be good news.  I realize there's still a lot of congestion, and in a worst case scenario, the issue can always be re-opened.  Good luck, Warriors of Macness!

**Comment by HereInPlainSight** [comment]
Little over a month and change, no reported issues, gonna close the issue.  Enjoy!
