### ISSUE TITLE
Installing gshade to a steam install running xivlauncher

### ISSUE THREAD

**Issue by Moosatronic** [HereInPlainSight/gshade_installer#15]
I'm not sure that currently when you install gshade to a proton prefix this script can deal with the fact that ffxiv might not be located at the default steam ffxiv location c://programfiles....etc etc., for example if you run xivlauncher and set your ffxiv install to somewhere outside of c://

I say this because i tried to install gshade to my prefix and while gshade is installed and works, I can't find the gshade presets

**Comment by HereInPlainSight** [comment]
That's -- odd.  So to confirm, you're getting the pop-up indicating that GShade is active and loaded when you log in at the top, you can open the GShade menu, you have the shaders... but not the presets?

I ask specifically because the script uses the same location for all of those things.  Once it finds ffxiv_dx11.exe, that's where it installs everything to at the same time.

_However_, Steam using XIVLauncher is a new development (as before, it was always recommended to install XIVLauncher through Lutris).  So Steam's files were always static.  Generally the script just put all those files into the nearby `/steamapps/common/FINAL FANTASY XIV Online/game/` location.  If XIVLauncher is installing locally, inside of the prefix, instead of in the default steam location, then it would make sense if _nothing_ was working.

The problem that it's working, but just missing the presets...  That's the unusual part.  Could you post your `./gshade_installer.sh debug` and a pic of your GShade path window, as below, please?  ![Screenshot_20220323_194924](https://user-images.githubusercontent.com/766446/159814907-84f73090-31d9-4810-8d94-0fcf25a386db.png)

**Comment by HereInPlainSight** [comment]
Over a month without further details -- if the issue persists, please comment / re-open!
