### ISSUE TITLE
xivlauncher no longer launching after install

### ISSUE THREAD

**Issue by Kromilan** [HereInPlainSight/gshade_installer#24]
Hello.
I just ran the installation script for ffxiv. it detected the wineprefix and the game location correctly. the installer said that it installed everything successfully. However since the install, the launcher starts as normal, but it no longer launches the game. the launcher window disappears as normal, but the game window never shows up. I read this is normal with the 32 bit version, but xivlauncher is using the 64 bit version.
I wish I could provide better info, like logs, but I am not sure where to find them or which logs would be relevant. I'll happily provide more information when you tell me which information you need.

**Comment by HereInPlainSight** [comment]
Can't say I've heard of this happening before.  You can post the info from `./gshade_installer.sh debug`, but also, does the game work again after removing GShade from it?  If not, have you upgraded your system / graphics drivers since your last reboot?  Is there a `GShade.log` file in the directory with the game itself (presumably `~/.xlcore/ffxiv/game/`)?

We don't even really touch the wine prefix any more with XIV (it's really only used in openGL games, now), it just makes some soft links in the game directory at this point, so the only thing that comes to mind is maybe a corrupt file download (everything can be re-downloaded with `./gshade_installer.sh fetchCompilers` and `./gshade_installer.sh update force`).

**Comment by Kromilan** [comment]
I am embarrassed to say this. I rebooted my computer and the issue persisted. I rebooted again, and it still persisted. I rebooted again and the issue was gone. I made no changes; it resolved itself on its own. So apparently I didn't really have an issue but simply bad luck. I am sorry that I bothered you.

**Comment by HereInPlainSight** [comment]
Not a problem at all -- glad you're up and running, strange as the solution was!  Closing out the issue, but if anything crops up, feel free to re-open or tag me in the GShade discord.  :)
